<?php

/**
 * @file
 * Custom field entity browser module file.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\custom_field_entity_browser\Hook\ConfigSchemaHooks;

/**
 * Implements hook_config_schema_info_alter().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
// phpcs:ignore Squiz.WhiteSpace.FunctionSpacing.Before
function custom_field_entity_browser_config_schema_info_alter(array &$definitions): void {
  \Drupal::service(ConfigSchemaHooks::class)->configSchemaInfoAlter($definitions);
}
