<?php

/**
 * @file
 * Seeds Components covering every string shape, without `derived_schema_metadata`.
 *
 * Two components together cover every string shape recognized by
 * \Drupal\canvas\PropShape\PropShape::getTranslatableStringShape(), plus
 * non-translatable props (string enum, email format, integer):
 * - `js.string_shapes` (2 versions: active + past) covers every shape a code
 *   component can express: plain string, the 4 URI-esque formats, rich text
 *   (`contentMediaType: text/html`) and an array of strings.
 * - `sdc.canvas_test_sdc.code-example` covers the multi-line `pattern` shape,
 *   which code components cannot express.
 *
 * The rows were generated by the current codebase, then every
 * `derived_schema_metadata` key was stripped: it is excluded from the version
 * hash, so the version ids remain valid — exactly the state of a site whose
 * config predates `derived_schema_metadata`.
 *
 * @see generate-components-with-string-shapes.php
 * @see \Drupal\Tests\canvas\Functional\Update\ComponentDerivedSchemaMetadataUpdateTest
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();

// Enable the test module that provides the `code-example` SDC, so the
// component source (and thus its metadata) is discoverable when the update
// runs.
$extension = $connection->select('config', 'c')
  ->fields('c', ['data'])
  ->condition('collection', '')
  ->condition('name', 'core.extension')
  ->execute()
  ->fetchField();
$extension = \unserialize($extension);
$extension['module']['canvas_test_sdc'] = 0;
// Keep the module list sorted by weight then name, as core does.
\uksort($extension['module'], static fn(string $a, string $b): int => [$extension['module'][$a], $a] <=> [$extension['module'][$b], $b]);
$connection->update('config')
  ->fields(['data' => \serialize($extension)])
  ->condition('collection', '')
  ->condition('name', 'core.extension')
  ->execute();

// Record the module's installed schema version (no hook_update_N == 8000).
$connection->merge('key_value')
  ->keys([
    'collection' => 'system.schema',
    'name' => 'canvas_test_sdc',
  ])
  ->fields(['value' => \serialize(8000)])
  ->execute();

$connection->insert('config')
  ->fields([
    'collection',
    'name',
    'data',
  ])
  ->values([
    'collection' => '',
    'name' => 'canvas.js_component.string_shapes',
    'data' => 'a:12:{s:4:"uuid";s:36:"f7f3193e-e7c8-4a34-959a-f4d212d47e7d";s:8:"langcode";s:2:"en";s:6:"status";b:1;s:12:"dependencies";a:0:{}s:11:"machineName";s:13:"string_shapes";s:4:"name";s:44:"Every string shape a code component supports";s:8:"required";a:0:{}s:5:"props";a:10:{s:5:"plain";a:3:{s:4:"type";s:6:"string";s:5:"title";s:12:"Plain string";s:8:"examples";a:1:{i:0;s:21:"Trigger a new version";}}s:3:"uri";a:4:{s:4:"type";s:6:"string";s:6:"format";s:3:"uri";s:5:"title";s:3:"URI";s:8:"examples";a:1:{i:0;s:19:"https://example.com";}}s:13:"uri_reference";a:4:{s:4:"type";s:6:"string";s:6:"format";s:13:"uri-reference";s:5:"title";s:13:"URI reference";s:8:"examples";a:1:{i:0;s:6:"/about";}}s:3:"iri";a:4:{s:4:"type";s:6:"string";s:6:"format";s:3:"iri";s:5:"title";s:3:"IRI";s:8:"examples";a:1:{i:0;s:30:"https://example.com/d%C3%BCrst";}}s:13:"iri_reference";a:4:{s:4:"type";s:6:"string";s:6:"format";s:13:"iri-reference";s:5:"title";s:13:"IRI reference";s:8:"examples";a:1:{i:0;s:6:"/about";}}s:9:"rich_text";a:5:{s:4:"type";s:6:"string";s:16:"contentMediaType";s:9:"text/html";s:20:"x-formatting-context";s:5:"block";s:5:"title";s:9:"Rich text";s:8:"examples";a:1:{i:0;s:20:"<p>Hello, world!</p>";}}s:11:"string_enum";a:5:{s:4:"type";s:6:"string";s:4:"enum";a:2:{i:0;s:3:"foo";i:1;s:3:"bar";}s:9:"meta:enum";a:2:{s:3:"foo";s:3:"Foo";s:3:"bar";s:3:"Bar";}s:5:"title";s:11:"String enum";s:8:"examples";a:1:{i:0;s:3:"foo";}}s:5:"email";a:4:{s:4:"type";s:6:"string";s:6:"format";s:5:"email";s:5:"title";s:5:"Email";s:8:"examples";a:1:{i:0;s:17:"hello@example.com";}}s:8:"quantity";a:3:{s:4:"type";s:7:"integer";s:5:"title";s:8:"Quantity";s:8:"examples";a:1:{i:0;i:3;}}s:7:"strings";a:4:{s:4:"type";s:5:"array";s:5:"items";a:1:{s:4:"type";s:6:"string";}s:5:"title";s:7:"Strings";s:8:"examples";a:1:{i:0;a:2:{i:0;s:5:"Hello";i:1;s:5:"world";}}}}s:5:"slots";a:0:{}s:2:"js";a:2:{s:8:"original";s:19:"console.log("hey");";s:8:"compiled";s:19:"console.log("hey");";}s:3:"css";a:2:{s:8:"original";s:0:"";s:8:"compiled";s:0:"";}s:16:"dataDependencies";a:0:{}}',
  ])
  ->values([
    'collection' => '',
    'name' => 'canvas.component.js.string_shapes',
    'data' => 'a:11:{s:4:"uuid";s:36:"6cdf119f-37db-4453-b696-405393c1b35b";s:8:"langcode";s:2:"en";s:6:"status";b:1;s:12:"dependencies";a:2:{s:6:"config";a:2:{i:0;s:33:"canvas.js_component.string_shapes";i:1;s:31:"filter.format.canvas_html_block";}s:6:"module";a:3:{i:0;s:4:"link";i:1;s:7:"options";i:2;s:4:"text";}}s:14:"active_version";s:16:"61c2c2d0c08e99fb";s:20:"versioned_properties";a:2:{s:6:"active";a:2:{s:8:"settings";a:1:{s:22:"prop_field_definitions";a:10:{s:5:"plain";a:7:{s:8:"required";b:0;s:10:"field_type";s:6:"string";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:16:"string_textfield";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:21:"Trigger a new version";}}s:10:"expression";s:20:"ℹ︎string␟value";}s:3:"uri";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:16;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:19:"https://example.com";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:13:"uri_reference";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:17;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:6:"/about";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:3:"iri";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:16;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:30:"https://example.com/d%C3%BCrst";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:13:"iri_reference";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:17;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:6:"/about";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:9:"rich_text";a:7:{s:8:"required";b:0;s:10:"field_type";s:9:"text_long";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:1:{s:15:"allowed_formats";a:1:{i:0;s:17:"canvas_html_block";}}s:12:"field_widget";s:13:"text_textarea";s:13:"default_value";a:1:{i:0;a:2:{s:5:"value";s:20:"<p>Hello, world!</p>";s:6:"format";s:17:"canvas_html_block";}}s:10:"expression";s:27:"ℹ︎text_long␟processed";}s:11:"string_enum";a:7:{s:8:"required";b:0;s:10:"field_type";s:11:"list_string";s:22:"field_storage_settings";a:1:{s:23:"allowed_values_function";s:45:"canvas_load_allowed_values_for_component_prop";}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:14:"options_select";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:3:"foo";}}s:10:"expression";s:25:"ℹ︎list_string␟value";}s:5:"email";a:7:{s:8:"required";b:0;s:10:"field_type";s:5:"email";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:13:"email_default";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:17:"hello@example.com";}}s:10:"expression";s:19:"ℹ︎email␟value";}s:8:"quantity";a:7:{s:8:"required";b:0;s:10:"field_type";s:7:"integer";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:6:"number";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";i:3;}}s:10:"expression";s:21:"ℹ︎integer␟value";}s:7:"strings";a:8:{s:8:"required";b:0;s:10:"field_type";s:6:"string";s:11:"cardinality";i:-1;s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:16:"string_textfield";s:13:"default_value";a:2:{i:0;a:1:{s:5:"value";s:5:"Hello";}i:1;a:1:{s:5:"value";s:5:"world";}}s:10:"expression";s:20:"ℹ︎string␟value";}}}s:17:"fallback_metadata";a:1:{s:16:"slot_definitions";a:0:{}}}s:16:"16b01eba802743e6";a:2:{s:8:"settings";a:1:{s:22:"prop_field_definitions";a:10:{s:5:"plain";a:7:{s:8:"required";b:0;s:10:"field_type";s:6:"string";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:16:"string_textfield";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:13:"Hello, world!";}}s:10:"expression";s:20:"ℹ︎string␟value";}s:3:"uri";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:16;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:19:"https://example.com";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:13:"uri_reference";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:17;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:6:"/about";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:3:"iri";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:16;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:30:"https://example.com/d%C3%BCrst";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:13:"iri_reference";a:7:{s:8:"required";b:0;s:10:"field_type";s:4:"link";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:2:{s:5:"title";i:0;s:9:"link_type";i:17;}s:12:"field_widget";s:12:"link_default";s:13:"default_value";a:1:{i:0;a:2:{s:3:"uri";s:6:"/about";s:7:"options";a:0:{}}}s:10:"expression";s:16:"ℹ︎link␟url";}s:9:"rich_text";a:7:{s:8:"required";b:0;s:10:"field_type";s:9:"text_long";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:1:{s:15:"allowed_formats";a:1:{i:0;s:17:"canvas_html_block";}}s:12:"field_widget";s:13:"text_textarea";s:13:"default_value";a:1:{i:0;a:2:{s:5:"value";s:20:"<p>Hello, world!</p>";s:6:"format";s:17:"canvas_html_block";}}s:10:"expression";s:27:"ℹ︎text_long␟processed";}s:11:"string_enum";a:7:{s:8:"required";b:0;s:10:"field_type";s:11:"list_string";s:22:"field_storage_settings";a:1:{s:23:"allowed_values_function";s:45:"canvas_load_allowed_values_for_component_prop";}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:14:"options_select";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:3:"foo";}}s:10:"expression";s:25:"ℹ︎list_string␟value";}s:5:"email";a:7:{s:8:"required";b:0;s:10:"field_type";s:5:"email";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:13:"email_default";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:17:"hello@example.com";}}s:10:"expression";s:19:"ℹ︎email␟value";}s:8:"quantity";a:7:{s:8:"required";b:0;s:10:"field_type";s:7:"integer";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:6:"number";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";i:3;}}s:10:"expression";s:21:"ℹ︎integer␟value";}s:7:"strings";a:8:{s:8:"required";b:0;s:10:"field_type";s:6:"string";s:11:"cardinality";i:-1;s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:16:"string_textfield";s:13:"default_value";a:2:{i:0;a:1:{s:5:"value";s:5:"Hello";}i:1;a:1:{s:5:"value";s:5:"world";}}s:10:"expression";s:20:"ℹ︎string␟value";}}}s:17:"fallback_metadata";a:1:{s:16:"slot_definitions";a:0:{}}}}s:5:"label";s:44:"Every string shape a code component supports";s:2:"id";s:16:"js.string_shapes";s:8:"provider";N;s:6:"source";s:2:"js";s:15:"source_local_id";s:13:"string_shapes";}',
  ])
  ->values([
    'collection' => '',
    'name' => 'canvas.component.sdc.canvas_test_sdc.code-example',
    'data' => 'a:11:{s:4:"uuid";s:36:"7111325c-8507-4d95-a014-af1d28c3a95b";s:8:"langcode";s:2:"en";s:6:"status";b:1;s:12:"dependencies";a:1:{s:6:"module";a:2:{i:0;s:15:"canvas_test_sdc";i:1;s:7:"options";}}s:14:"active_version";s:16:"9ba0b4240a0e8ffd";s:20:"versioned_properties";a:1:{s:6:"active";a:2:{s:8:"settings";a:1:{s:22:"prop_field_definitions";a:2:{s:8:"language";a:7:{s:8:"required";b:0;s:10:"field_type";s:11:"list_string";s:22:"field_storage_settings";a:1:{s:23:"allowed_values_function";s:45:"canvas_load_allowed_values_for_component_prop";}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:14:"options_select";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:3:"php";}}s:10:"expression";s:25:"ℹ︎list_string␟value";}s:4:"code";a:7:{s:8:"required";b:1;s:10:"field_type";s:11:"string_long";s:22:"field_storage_settings";a:0:{}s:23:"field_instance_settings";a:0:{}s:12:"field_widget";s:15:"string_textarea";s:13:"default_value";a:1:{i:0;a:1:{s:5:"value";s:28:"<?php
echo \'Hello, world!\';
";}}s:10:"expression";s:25:"ℹ︎string_long␟value";}}}s:17:"fallback_metadata";a:1:{s:16:"slot_definitions";a:0:{}}}}s:5:"label";s:12:"Code Example";s:2:"id";s:32:"sdc.canvas_test_sdc.code-example";s:8:"provider";s:15:"canvas_test_sdc";s:6:"source";s:3:"sdc";s:15:"source_local_id";s:28:"canvas_test_sdc:code-example";}',
  ])
  ->execute();
