<?php

/**
 * @file
 * Custom field Graphql module file.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\custom_field_graphql\Hook\CustomFieldGraphqlHooks;

/**
 * Implements hook_graphql_compose_field_type_form_alter().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
// phpcs:ignore Squiz.WhiteSpace.FunctionSpacing.Before
function custom_field_graphql_graphql_compose_field_type_form_alter(array &$form, FormStateInterface $form_state, FieldDefinitionInterface $field, array $settings): void {
  \Drupal::service(CustomFieldGraphqlHooks::class)->graphqlComposeFieldTypeFormAlter($form, $form_state, $field, $settings);
}

/**
 * Implements hook_config_schema_info_alter().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
// phpcs:ignore Squiz.WhiteSpace.FunctionSpacing.Before
function custom_field_graphql_config_schema_info_alter(array &$definitions): void {
  \Drupal::service(CustomFieldGraphqlHooks::class)->configSchemaInfoAlter($definitions);
}
