name: "Composer validations"
description: "Run composer validations such PHPCS, PHPStan and Composer audit"

inputs:
  php_version:
    description: "PHP Version to run."
    default: "8.2"
  composer_version:
    description: "Composer version to run."
    default: "2"

runs:
  using: "composite"
  steps:
    - name: "Setup PHP"
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}
        extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
        coverage: none

    - name: Validate the syntax of the composer.json file
      shell: bash
      run: composer validate --no-check-all

    - name: Check composer.lock
      shell: bash
      run: |
        composer install--dry-run
        if [ $? -ne 0 ]; then
          echo "composer.lock is out of date. Please run 'composer update' to generate an updated lock file."
          exit 1
        fi

    - name: Cache Composer dependencies
      uses: actions/cache@v5
      with:
        path: ~/.cache/composer
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies via composer
      uses: php-actions/composer@v6
      env:
        COMPOSER: "composer.json"
      with:
        php_version: ${{ inputs.php_version }}
        version: ${{ inputs.composer_version }}
        args: "--ignore-platform-reqs --no-progress --no-interaction --prefer-dist --optimize-autoloader"
