<?php

/**
 * @file
 * Install, update and uninstall functions for the amazee.ai AI Provider module.
 */

declare(strict_types=1);

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\ai_provider_amazeeio\Plugin\AiProvider\AmazeeioAiProvider;

/**
 * Install AI Search.
 */
function ai_provider_amazeeio_update_10001(): void {
  \Drupal::service('module_installer')
    ->install(['ai_search']);
}

/**
 * Implements hook_uninstall().
 */
function ai_provider_amazeeio_uninstall(): void {
  // Delete the keys created by this module.
  $keys_to_delete = ['amazeeio_ai_database', 'amazeeio_ai'];
  $key_storage = \Drupal::entityTypeManager()->getStorage('key');
  foreach ($keys_to_delete as $key_id) {
    if ($key = $key_storage->load($key_id)) {
      $key->delete();
    }
  }
}

/**
 * Implements hook_update_N().
 *
 * Set default model for chat_with_tools and chat_with_structured_response
 * if not set.
 */
function ai_provider_amazeeio_update_10002(): TranslatableMarkup {
  $ai_provider = \Drupal::service('ai.provider');
  // By default, it has not changed anything.
  $return_message = \Drupal::translation()->translate('No changes made to amazee.ai provider default models.');
  foreach (['chat_with_tools', 'chat_with_structured_response'] as $type) {
    // If TRUE, it meant that it was needed to be set.
    if ($ai_provider->defaultIfNone($type, AmazeeioAiProvider::PROVIDER_ID, 'claude-3-5-sonnet')) {
      $return_message = \Drupal::translation()->translate('amazee.ai provider default model set for relevant chat operation types.');
    }
  }
  return $return_message;
}
