/**
 * @file
 * Build-time generation of the component implementation registry consumed by
 * framework adapters. Node-only: discovery reads the app filesystem.
 */

import path from 'node:path';
import {
  discoverCanvasProject,
  loadComponentsMetadata,
  resolveCanvasConfig,
} from '@drupal-canvas/discovery';

import { COMPONENT_ENTRY_EXTENSIONS } from './component-entry-extensions';

export interface ComponentRegistryOptions {
  /** The app directory containing canvas.config.json. Default: process.cwd(). */
  projectRoot?: string;
  /**
   * Filesystem path of the generated module. When present, entry imports are
   * relative to this file; otherwise absolute imports are generated for a
   * framework virtual module.
   */
  modulePath?: string;
}

export interface ComponentRegistrySourcePaths {
  /** The app's Canvas configuration file. */
  configPath: string;
  /** The component discovery root selected by the current configuration. */
  componentRoot: string;
}

/**
 * Generates a module with one static default import per discovered component.
 *
 * Static imports let each framework bundler trace the implementations while
 * component discovery keeps the registry synchronized with component.yml.
 * Duplicate machine names follow the Drupal reader's policy: the first wins.
 */
export async function buildComponentRegistryModule(
  options: ComponentRegistryOptions = {},
): Promise<string> {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd());
  const config = resolveCanvasConfig({ hostRoot: projectRoot });
  const result = await discoverCanvasProject({
    componentRoot: path.resolve(projectRoot, config.componentDir),
    pagesRoot: path.resolve(projectRoot, config.pagesDir),
    projectRoot,
    entryExtensions: COMPONENT_ENTRY_EXTENSIONS,
  });
  const metadata = await loadComponentsMetadata(result);
  const seenMachineNames = new Set<string>();
  const entries = metadata.flatMap((component, index) => {
    const discovered = result.components[index];
    if (
      !discovered?.jsEntryPath ||
      seenMachineNames.has(component.machineName)
    ) {
      return [];
    }
    seenMachineNames.add(component.machineName);
    return [
      {
        machineName: component.machineName,
        importPath: getImportPath(discovered.jsEntryPath, options.modulePath),
      },
    ];
  });

  const imports = entries.map(
    ({ importPath }, index) =>
      `import Component${index} from ${JSON.stringify(importPath)};`,
  );
  const registry = entries.map(
    ({ machineName }, index) =>
      `  ${JSON.stringify(machineName)}: Component${index},`,
  );

  return [
    '/** Generated by the Drupal Canvas Headless SDK. */',
    ...imports,
    '',
    'const components = {',
    ...registry,
    '};',
    '',
    'export default components;',
    '',
  ].join('\n');
}

/** Resolves the configured source locations used to build the registry. */
export function resolveComponentRegistrySourcePaths(
  options: Pick<ComponentRegistryOptions, 'projectRoot'> = {},
): ComponentRegistrySourcePaths {
  const projectRoot = path.resolve(options.projectRoot ?? process.cwd());
  const config = resolveCanvasConfig({ hostRoot: projectRoot });
  return {
    configPath: path.join(projectRoot, 'canvas.config.json'),
    componentRoot: path.resolve(projectRoot, config.componentDir),
  };
}

function getImportPath(entryPath: string, modulePath?: string): string {
  if (!modulePath) {
    return normalizePath(entryPath);
  }
  const relativePath = normalizePath(
    path.relative(path.dirname(modulePath), entryPath),
  );
  return relativePath.startsWith('.') ? relativePath : `./${relativePath}`;
}

function normalizePath(filePath: string): string {
  return filePath.split(path.sep).join('/');
}
