<?php

/**
 * @file
 * Post-update functions for the Canvas AI module.
 */

declare(strict_types=1);

use Drupal\canvas\Plugin\Canvas\ComponentSource\BlockComponent;
use Drupal\canvas\Plugin\Canvas\ComponentSource\JsComponent;
use Drupal\canvas\Plugin\Canvas\ComponentSource\SingleDirectoryComponent;
use Drupal\canvas_ai\CanvasAiPageBuilderHelper;
use Drupal\Component\Serialization\Yaml;
use Drupal\Component\Utility\Crypt;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Config\FileStorage;

/**
 * Rebuild the router.
 *
 * Clears the route cache as this issue introduces changes to canvas_ai routes.
 *
 * @see https://www.drupal.org/project/canvas/issues/3533079
 */
function canvas_ai_post_update_0001_rebuild_router(): void {
  \Drupal::service('router.builder')->rebuild();
}

/**
 * Preserve the existing chat history limit for existing sites.
 */
function canvas_ai_post_update_0002_chat_history_max_messages(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.settings');

  // Existing sites effectively use a limit of 3, so keep that value here to
  // preserve current behavior. New installations get the newer default of
  // 10 from config/install/canvas_ai.settings.yml.
  if (!$config->isNew()) {
    $config->set('chat_history_max_messages', 3)->save(TRUE);
  }
}

/**
 * Reimport orchestrator agent as system prompt has changed.
 *
 * @see https://www.drupal.org/project/canvas/issues/3582390
 */
function canvas_ai_post_update_0003_reimport_orchestrator_agent(): void {
  $module_path = \Drupal::service('extension.list.module')->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $data = $source->read('ai_agents.ai_agent.canvas_ai_orchestrator');
  $config = \Drupal::configFactory()->getEditable('ai_agents.ai_agent.canvas_ai_orchestrator');
  if ($data && !$config->isNew()) {
    // Only the system prompt changed. Set just that key so the per-site uuid,
    // _core hash, and any other fields stay intact.
    $config->set('system_prompt', $data['system_prompt'])->save(TRUE);

    $message = 'The Canvas AI orchestrator agent system prompt has been updated. If you had customized it directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}

/**
 * Enable hostname filter bypass for the Canvas Component Agent.
 *
 * Hostname filtering will interfere with the React code generated by
 * canvas_component_agent, so it must be disabled for the agent to work correctly.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3590309
 */
function canvas_ai_post_update_0004_agent_hostname_filter(): void {
  $config = \Drupal::configFactory()
    ->getEditable('ai_agents.ai_agent.canvas_component_agent');
  if (!$config->isNew() && $config->get('hostname_filter_disabled') !== TRUE) {
    $config->set('hostname_filter_disabled', TRUE)->save(TRUE);
  }
}

/**
 * Normalize component description settings for stricter schema validation.
 */
function canvas_ai_post_update_0005_normalize_component_description_settings(): void {
  $config_factory = Drupal::service('config.factory');
  assert($config_factory instanceof ConfigFactoryInterface);
  $config = $config_factory->getEditable('canvas_ai.component_description.settings');

  if ($config->isNew()) {
    // The settings form creates this config on first save. Sites that never
    // saved it have no active config to normalize.
    return;
  }

  $context = $config->get('component_context') ?? [];
  $allowed_sources = [
    SingleDirectoryComponent::SOURCE_PLUGIN_ID,
    JsComponent::SOURCE_PLUGIN_ID,
    BlockComponent::SOURCE_PLUGIN_ID,
  ];
  $migrated = [];

  // Active configuration may predate schema validation or have been imported
  // with invalid values, so normalize only the array shape this update supports.
  foreach (is_array($context) ? $context : [] as $source => $entry) {
    if (!in_array($source, $allowed_sources, TRUE)) {
      continue;
    }

    if (!is_array($entry)) {
      $entry = [];
    }

    $data = (string) ($entry['data'] ?? '');
    if (trim($data) === '') {
      $data = "{}\n";
    }

    $migrated[$source] = [
      'enabled' => (bool) ($entry['enabled'] ?? FALSE),
      'data' => $data,
    ];
  }

  ksort($migrated);
  $config->set('component_context', $migrated)->save(TRUE);
}

/**
 * Restore the uuid and _core hash stripped from the orchestrator by 0003.
 *
 * The 1.5.0/1.5.1 release of post_update 0003 replaced the whole record via
 * setData(), dropping the system-managed uuid and _core keys that the install
 * file omits. So regenerate both
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3591660
 */
function canvas_ai_post_update_0006_restore_orchestrator_agent_uuid(): void {
  $name = 'ai_agents.ai_agent.canvas_ai_orchestrator';
  $config = \Drupal::configFactory()->getEditable($name);
  if ($config->isNew()) {
    return;
  }

  $changed = FALSE;
  if (empty($config->get('uuid'))) {
    $config->set('uuid', \Drupal::service('uuid')->generate());
    $changed = TRUE;
  }
  if (empty($config->get('_core.default_config_hash'))) {
    // Recompute the hash exactly as core does when installing config
    // @see \Drupal\Core\Config\ConfigInstaller::createConfiguration()
    $module_path = \Drupal::service('extension.list.module')->getPath('canvas_ai');
    $install = (new FileStorage($module_path . '/config/install'))->read($name);
    $config->set('_core.default_config_hash', Crypt::hashBase64(serialize($install)));
    $changed = TRUE;
  }
  if ($changed) {
    $config->save(TRUE);
  }
}

/**
 * Add block component props to saved component description settings.
 *
 * Block components previously stored only id/name/description. They now also
 * expose props, so rebuild the saved block data from the live system and merge
 * back any user-customized descriptions.
 *
 * @see \Drupal\canvas_ai\CanvasAiPageBuilderHelper::getEnabledBlockComponentsFromStorage()
 */
function canvas_ai_post_update_0007_add_block_props_to_component_description_settings(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.component_description.settings');
  if ($config->isNew()) {
    return;
  }

  $source = BlockComponent::SOURCE_PLUGIN_ID;
  $saved_data = (string) $config->get("component_context.$source.data");
  // Nothing to migrate when the site never saved any block data.
  if ($saved_data === '') {
    return;
  }

  $page_builder_helper = \Drupal::service('canvas_ai.page_builder_helper');
  assert($page_builder_helper instanceof CanvasAiPageBuilderHelper);
  $rebuilt_blocks = $page_builder_helper->getEnabledBlockComponentsFromStorage();
  // Without live block data there are no props to add.
  if ($rebuilt_blocks === []) {
    return;
  }

  // The rebuilt data already carries the new props and their default
  // descriptions. Layer each block's previously saved description back on top.
  $decoded = Yaml::decode($saved_data);
  $saved_blocks = is_array($decoded) ? $decoded : [];
  foreach ($saved_blocks as $block_id => $saved_block) {
    if (isset($rebuilt_blocks[$block_id], $saved_block['description'])) {
      $rebuilt_blocks[$block_id]['description'] = $saved_block['description'];
    }
  }

  // Replace only the block data; the enabled flag is left untouched.
  $config->set("component_context.$source.data", Yaml::encode($rebuilt_blocks))->save(TRUE);
}

/**
 * Reimport the component agent as its system prompt and tokens have changed.
 *
 * The conditional state instructions were moved out of the system prompt into
 * a dynamic section injected through the new component_agent_dynamic_state
 * token, so existing sites need the stored agent config refreshed.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3584136
 */
function canvas_ai_post_update_0008_reimport_component_agent(): void {
  $module_path = \Drupal::service('extension.list.module')->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $data = $source->read('ai_agents.ai_agent.canvas_component_agent');
  $config = \Drupal::configFactory()->getEditable('ai_agents.ai_agent.canvas_component_agent');
  if ($data && !$config->isNew()) {
    // Only the system prompt and tool usage limits changed.
    $config
      ->set('system_prompt', $data['system_prompt'])
      ->set('tool_usage_limits', $data['tool_usage_limits'])
      ->save(TRUE);

    $message = 'The Canvas component agent system prompt has been updated. If you had customized it directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}
