<?php

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

function canvas_test_native_value_js_form_component_instance_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['text_trigger'] = [
    '#type' => 'button',
    '#value' => 'Trigger Text Update',
    '#attributes' => [
      'id' => 'trigger-text-update',
    ],
  ];
  $form['select_trigger'] = [
    '#type' => 'button',
    '#value' => 'Trigger Select Update',
    '#attributes' => [
      'id' => 'trigger-select-update',
    ],
  ];
  $form['number_trigger'] = [
    '#type' => 'button',
    '#value' => 'Trigger Number Update',
    '#attributes' => [
      'id' => 'trigger-number-update',
    ],
  ];
  $form['toggle_trigger'] = [
    '#type' => 'button',
    '#value' => 'Trigger Toggle',
    '#attributes' => [
      'id' => 'trigger-toggle-update',
    ],
  ];
  $form['checkbox_trigger'] = [
    '#type' => 'button',
    '#value' => 'Trigger Checkbox Update',
    '#attributes' => [
      'id' => 'trigger-checkbox-update',
    ],
  ];
  $form['#attached']['library'][] = 'canvas_test_native_value_js/test';
}
