/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDraftRouteImport } from './routes/api/draft'
import { Route as ApiDisableDraftRouteImport } from './routes/api/disable-draft'
import { Route as ApiDraftRenewRouteImport } from './routes/api/draft.renew'
import { Route as ApiCanvasComponentsRouteImport } from './routes/api/canvas.components'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisableDraftRoute = ApiDisableDraftRouteImport.update({
  id: '/api/disable-draft',
  path: '/api/disable-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRenewRoute = ApiDraftRenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => ApiDraftRoute,
} as any)
const ApiCanvasComponentsRoute = ApiCanvasComponentsRouteImport.update({
  id: '/api/canvas/components',
  path: '/api/canvas/components',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/disable-draft': typeof ApiDisableDraftRoute
  '/api/draft': typeof ApiDraftRouteWithChildren
  '/api/canvas/components': typeof ApiCanvasComponentsRoute
  '/api/draft/renew': typeof ApiDraftRenewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/disable-draft': typeof ApiDisableDraftRoute
  '/api/draft': typeof ApiDraftRouteWithChildren
  '/api/canvas/components': typeof ApiCanvasComponentsRoute
  '/api/draft/renew': typeof ApiDraftRenewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/disable-draft': typeof ApiDisableDraftRoute
  '/api/draft': typeof ApiDraftRouteWithChildren
  '/api/canvas/components': typeof ApiCanvasComponentsRoute
  '/api/draft/renew': typeof ApiDraftRenewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/disable-draft'
    | '/api/draft'
    | '/api/canvas/components'
    | '/api/draft/renew'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/disable-draft'
    | '/api/draft'
    | '/api/canvas/components'
    | '/api/draft/renew'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/disable-draft'
    | '/api/draft'
    | '/api/canvas/components'
    | '/api/draft/renew'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiDisableDraftRoute: typeof ApiDisableDraftRoute
  ApiDraftRoute: typeof ApiDraftRouteWithChildren
  ApiCanvasComponentsRoute: typeof ApiCanvasComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disable-draft': {
      id: '/api/disable-draft'
      path: '/api/disable-draft'
      fullPath: '/api/disable-draft'
      preLoaderRoute: typeof ApiDisableDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft/renew': {
      id: '/api/draft/renew'
      path: '/renew'
      fullPath: '/api/draft/renew'
      preLoaderRoute: typeof ApiDraftRenewRouteImport
      parentRoute: typeof ApiDraftRoute
    }
    '/api/canvas/components': {
      id: '/api/canvas/components'
      path: '/api/canvas/components'
      fullPath: '/api/canvas/components'
      preLoaderRoute: typeof ApiCanvasComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDraftRouteChildren {
  ApiDraftRenewRoute: typeof ApiDraftRenewRoute
}

const ApiDraftRouteChildren: ApiDraftRouteChildren = {
  ApiDraftRenewRoute: ApiDraftRenewRoute,
}

const ApiDraftRouteWithChildren = ApiDraftRoute._addFileChildren(
  ApiDraftRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiDisableDraftRoute: ApiDisableDraftRoute,
  ApiDraftRoute: ApiDraftRouteWithChildren,
  ApiCanvasComponentsRoute: ApiCanvasComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
