<?php

/**
 * @file
 * Hooks for the sitemap_vocabulary_api_test module.
 */

/**
 * Implements hook_sitemap_vocabulary_alter().
 */
function sitemap_vocabulary_api_test_sitemap_vocabulary_alter(array &$list, string $vid): void {
  if ($vid === 'tags') {
    // Hide term with ID 5.
    if (\array_key_exists(5, $list)) {
      unset($list[5]);
    }

    // Add a string to the end of every term with an even term ID.
    foreach ($list as $tid => $termContainer) {
      if ($tid % 2 === 0) {
        $list[$tid]['data']['#name'] .= ' ' . t('[Cool]');
      }
    }
  }
}

/**
 * Implements hook_sitemap_vocabulary_VID_alter() for 'genres'.
 */
function sitemap_vocabulary_api_test_sitemap_vocabulary_genres_alter(array &$list, string $vid): void {
  // Add text between each top-level term and its sub-terms.
  foreach ($list as $key => $value) {
    if (isset($value['children'])) {
      $list[$key][] = ['#markup' => ' ' . t('with sub-terms...')];

      // We have to give the sub-term list a weight so it "sinks" below the
      // new text.
      $list[$key]['children']['#weight'] = 10;
    }
  }
}
