<?php

/**
 * @file
 * Legacy hooks for Navigation Extra Tools module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\navigation_extra_tools\Hook\NavigationExtraToolsHooks;

/**
 * Implements hook_library_info_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function navigation_extra_tools_library_info_alter(&$libraries, $extension) {
  \Drupal::service(NavigationExtraToolsHooks::class)->libraryInfoAlter($libraries, $extension);
}

/**
 * Implements hook_page_attachments().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function navigation_extra_tools_page_attachments(array &$page) {
  \Drupal::service(NavigationExtraToolsHooks::class)->pageAttachments($page);
}

/**
 * Implements hook_modules_installed().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function navigation_extra_tools_modules_installed($modules, $is_syncing) {
  \Drupal::service(NavigationExtraToolsHooks::class)->modulesInstalled($modules, $is_syncing);
}
