<?php

/**
 * @file
 * Custom field sdc module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\custom_field_sdc\Hook\EntityHooks;
use Drupal\custom_field_sdc\Hook\FormHooks;

/**
 * Implements hook_form_BASE_FORM_ID_alter() for entity_view_display_edit_form.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
// phpcs:ignore Squiz.WhiteSpace.FunctionSpacing.Before
function custom_field_sdc_form_entity_view_display_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id): void {
  \Drupal::service(FormHooks::class)->formEntityViewDisplayEditFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_view_alter().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
// phpcs:ignore Squiz.WhiteSpace.FunctionSpacing.Before
function custom_field_sdc_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display): void {
  \Drupal::service(EntityHooks::class)->entityViewAlter($build, $entity, $display);
}
