<?php

declare(strict_types=1);

namespace Drupal\Tests\canvas\Functional;

// cspell:ignore Bienvenue savoir Découvrez Identité visuelle Charte graphique

use Behat\Mink\Element\NodeElement;
use Drupal\canvas\Entity\ContentTemplate;
use Drupal\canvas\Hook\TmgmtHooks;
use Drupal\canvas\Tmgmt\ComponentInputsConfigProcessor;
use Drupal\Core\Extension\ModuleInstallerInterface;
use Drupal\Tests\tmgmt\Functional\TmgmtTestTrait;
use Drupal\tmgmt\Entity\Job;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;
use PHPUnit\Framework\Attributes\Group;

/**
 * @see \Drupal\Tests\canvas\Functional\ContentWithComponentTreeTmgmtUiTest
 */
#[Group('canvas')]
#[Group('canvas_translation')]
#[CoversClass(ComponentInputsConfigProcessor::class)]
#[CoversMethod(TmgmtHooks::class, 'configSchemaInfoAlter')]
class ConfigWithComponentTreeTmgmtUiTest extends ConfigWithComponentTreeTranslationTestBase {

  use TmgmtTestTrait;

  public function test(): void {
    $module_installer = $this->container->get('module_installer');
    \assert($module_installer instanceof ModuleInstallerInterface);
    $module_installer->install(['tmgmt', 'tmgmt_config', 'tmgmt_test']);
    // Rebuild necessary for TMGMT-specific config schema changes.
    // @see \Drupal\canvas\Hook\TmgmtHooks::configSchemaInfoAlter()
    $this->rebuildContainer();

    $translator = $this->createTranslator([
      'name' => 'test_tmgmt',
      'label' => 'Test TMGMT',
      // @see \Drupal\tmgmt_test\Plugin\tmgmt\Translator\TestTranslator
      'plugin' => 'test_translator',
      'remote_languages_mappings' => [],
      'settings' => ['key' => 'test', 'another_key' => 'test'],
    ]);

    $job = $this->createJob('en', 'fr', $this->rootUser->id(), ['translator' => $translator->id()]);
    $job_item = $job->addItem('config', ContentTemplate::ENTITY_TYPE_ID, self::CONFIG_NAME);

    $job->setState(Job::STATE_ACTIVE);
    $translator->getPlugin()->requestTranslation($job);

    $this->drupalGet('admin/tmgmt/items/' . $job_item->id());
    $assert = $this->assertSession();
    $assert->statusCodeEquals(200);

    // Assert source texts visible for all edge cases.
    // Multiple-cardinality: each tag shown individually.
    $assert->pageTextContains('baz');
    $assert->pageTextContains('bar');
    $assert->pageTextContains('foo');
    // Plain prose.
    $assert->pageTextContains('Press');
    // URI-esque: requires `field.value.link` alteration.
    // @see \Drupal\canvas\Hook\ConfigTranslationHooks::configSchemaInfoAlter()
    $assert->pageTextContains('https://www.drupal.org');
    // Banner plain prose.
    $assert->pageTextContains('A heading element! :)');
    // Rich prose: only value extracted, not format.
    $assert->pageTextContains('In a curious work, published in');

    // Assert translations generated by test_translator (prefix "fr: ").
    $assert->pageTextContains('fr: baz');
    $assert->pageTextContains('fr: bar');
    $assert->pageTextContains('fr: foo');
    $assert->pageTextContains('fr: Press');
    $assert->pageTextContains('fr: https://www.drupal.org');
    $assert->pageTextContains('fr: A heading element! :)');

    // Explicitly assert all the form fields that exist per component instance,
    // to prove the generated UI matches expectations.
    self::assertSame([
      self::UUID_TAGS => [
        'component_tree|' . self::UUID_TAGS . '|inputs|tags|0[translation]',
        'component_tree|' . self::UUID_TAGS . '|inputs|tags|1[translation]',
        'component_tree|' . self::UUID_TAGS . '|inputs|tags|2[translation]',
      ],
      // @todo Consider respecting the defined order of props; the config_translation UI does support that.
      self::UUID_MY_HERO => [
        // SDC props populated by StaticPropSources are translatable.
        'component_tree|' . self::UUID_MY_HERO . '|inputs|heading[translation]',
        'component_tree|' . self::UUID_MY_HERO . '|inputs|cta2[translation]',

        // ⚠️ SDC prop populated by EntityFieldPropSource is NOT translatable:
        // that would have listed `…|inputs|cta1[translation]`, too.

        // ⚠️ SDC prop populated by HostEntityUrlPropSource is NOT translatable:
        // that would have listed `…|inputs|cta1href[translation]`, too.

        // Optional prop NOT populated in default is translatable: a translation
        // may opt to populate it even when the default translation leaves it
        // empty.
        // @see \Drupal\canvas\Tmgmt\ComponentInputsConfigProcessor::extractTranslatablesIncludingEmpty()
        'component_tree|' . self::UUID_MY_HERO . '|inputs|subheading[translation]',
      ],
      self::UUID_MY_CTA => [
        'component_tree|' . self::UUID_MY_CTA . '|inputs|text[translation]',
        'component_tree|' . self::UUID_MY_CTA . '|inputs|href|uri[translation]',
      ],
      self::UUID_BANNER => [
        'component_tree|' . self::UUID_BANNER . '|inputs|heading[translation]',
        'component_tree|' . self::UUID_BANNER . '|inputs|text|value[translation][value]',
        // Text format is present to load CKEditor 5, but is immutable because
        // it is an `input[type=hidden]`. See the next assertion.
        'component_tree|' . self::UUID_BANNER . '|inputs|text|value[translation][format]',
      ],
      // Branding block: only `label` is translatable.
      self::UUID_BRANDING => [
        'component_tree|' . self::UUID_BRANDING . '|inputs|label[translation]',
      ],
      // Translatability test block: only `label` and the deeply nested `bar`
      // are translatable.
      self::UUID_BLOCK_DEEP_TRANSLATABLE => [
        'component_tree|' . self::UUID_BLOCK_DEEP_TRANSLATABLE . '|inputs|label[translation]',
        'component_tree|' . self::UUID_BLOCK_DEEP_TRANSLATABLE . '|inputs|deeply_nested_translatable|0|bar[translation]',
      ],
      // Block whose translatable `name` is empty in the source language: it is
      // still offered for translation (shown via the `∅` placeholder),
      // alongside the populated `label`.
      self::UUID_BLOCK_EMPTY_TRANSLATABLE_INPUT => [
        'component_tree|' . self::UUID_BLOCK_EMPTY_TRANSLATABLE_INPUT . '|inputs|label[translation]',
        'component_tree|' . self::UUID_BLOCK_EMPTY_TRANSLATABLE_INPUT . '|inputs|name[translation]',
      ],
      // untranslatable-prop-shapes component: no prop shape is translatable, so
      // none is offered for translation. `date` (datetime field, date-only),
      // `email`, `integer` and `boolean` are all excluded.
      self::UUID_UNTRANSLATABLE_PROP_SHAPES => [],
    ], $this->getTmgmtFormElementsForComponentInstances());
    // The "format" input exists (to load CKEditor) but is hidden, so it cannot
    // be changed.
    $assert->elementExists(
      'css',
      'input[type="hidden"][name="component_tree|' . self::UUID_BANNER . '|inputs|text|value[translation][format]"]',
    );

    // Note: all other translatables get a `fr: ` prefix by the test translator.
    $this->submitForm([
      'component_tree|' . self::UUID_MY_HERO . '|inputs|subheading[translation]' => 'Découvrez Canvas',
      'component_tree|' . self::UUID_MY_HERO . '|inputs|heading[translation]' => 'Bienvenue à Canvas',
      'component_tree|' . self::UUID_MY_HERO . '|inputs|cta2[translation]' => 'En savoir plus',
      'component_tree|' . self::UUID_MY_CTA . '|inputs|href|uri[translation]' => 'https://fr.drupal.org',
      // Each block's `label` is empty in the source language; translate it
      // explicitly so the test translator does not map `∅` to `fr: ∅`.
      'component_tree|' . self::UUID_BRANDING . '|inputs|label[translation]' => 'Identité visuelle',
      'component_tree|' . self::UUID_BLOCK_DEEP_TRANSLATABLE . '|inputs|label[translation]' => 'fr: Canvas Test Block for testing input translatability',
      'component_tree|' . self::UUID_BLOCK_EMPTY_TRANSLATABLE_INPUT . '|inputs|label[translation]' => 'fr: Test block with settings',
      // The block's `name` is also empty in the source language.
      'component_tree|' . self::UUID_BLOCK_EMPTY_TRANSLATABLE_INPUT . '|inputs|name[translation]' => 'Charte graphique',
    ], 'Save as completed');
    $assert->pageTextContains('has been accepted');

    $this->assertTranslatedConfigComponentTree();
  }

  private function getTmgmtFormElementsForComponentInstances(): array {
    $page = $this->getSession()->getPage();

    $form_field_names = [];
    foreach (\array_keys(self::COMPONENT_DELTA) as $component_instance_uuid) {
      $form_field_names[$component_instance_uuid] = \array_map(
        fn(NodeElement $n) => $n->getAttribute('name'),
        $page->findAll('css', "[name*='component_tree|$component_instance_uuid|inputs'][name*='[translation]']"),
      );
    }
    return $form_field_names;
  }

}
