import fs from 'fs/promises';
import path from 'path';

import agentsContextProviders from './agents-context-providers';

import type { Command } from 'commander';
import type { ApiService } from '../services/api';

export interface AgentsContextProviderInput {
  apiService: ApiService;
  writeContextFile: (filename: string, data: unknown) => Promise<string>;
  writeMessage: (message: string) => void;
  writeOutput: (data: unknown) => void;
  arguments: string[];
}

export interface AgentsContextProvider {
  name: string;
  description: string;
  aliases?: string[];
  default: boolean;
  execute: (input: AgentsContextProviderInput) => Promise<void>;
}

export const AGENTS_CONTEXT_DIR = path.join('.agents', 'drupal-canvas');

export interface PullAgentsContextOptions {
  provider?: string;
  providerArgs?: string[];
  writeMessage?: (message: string) => void;
  writeOutput?: (data: unknown) => void;
  runAll?: boolean;
}

export async function pullAgentsContext(
  apiService: ApiService,
  projectRoot: string,
  options: PullAgentsContextOptions = {},
): Promise<void> {
  const {
    provider,
    providerArgs = [],
    writeMessage = (message: string) => {
      process.stdout.write(`${message}\n`);
    },
    writeOutput = (data: unknown) => {
      process.stdout.write(`${JSON.stringify(data)}\n`);
    },
    runAll = false,
  } = options;
  const outDir = path.join(projectRoot, AGENTS_CONTEXT_DIR);
  const writeContextFile = async (
    filename: string,
    data: unknown,
  ): Promise<string> => {
    const filePath = path.join(outDir, filename);
    await fs.mkdir(outDir, { recursive: true });
    await fs.writeFile(filePath, JSON.stringify(data) + '\n', 'utf-8');
    return path.relative(projectRoot, filePath);
  };

  const providers = selectAgentsContextProviders(provider, runAll);
  const providerInput = {
    apiService,
    writeContextFile,
    writeMessage,
    writeOutput,
    arguments: providerArgs,
  };

  await Promise.all([
    ...providers.map((provider) => provider.execute(providerInput)),
    (async () => {
      await fs.mkdir(outDir, { recursive: true });
      await fs.writeFile(
        path.join(outDir, '.gitignore'),
        '# Generated by `canvas agents-context`.\n*\n',
        'utf-8',
      );
    })(),
  ]);
}

export function formatAgentsContextProviders(command?: Command): string {
  if (command) {
    const helper = command.createHelp();
    helper.prepareContext({});
    const termWidth = Math.max(
      helper.padWidth(command, helper),
      ...agentsContextProviders.map((provider) =>
        helper.displayWidth(formatProviderTerm(provider)),
      ),
    );
    const providerItems = agentsContextProviders.map((provider) =>
      helper.formatItem(
        helper.styleSubcommandTerm(formatProviderTerm(provider)),
        termWidth,
        helper.styleSubcommandDescription(
          formatProviderDescription(provider.description, termWidth),
        ),
        helper,
      ),
    );
    return helper
      .formatItemList('Available context providers:', providerItems, helper)
      .join('\n');
  }

  const lines = ['', 'Available context providers:'];
  for (const provider of agentsContextProviders) {
    lines.push(`  ${formatProviderTerm(provider)}`);
    lines.push(`    ${provider.description.replace(/\n/g, '\n    ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

function formatProviderTerm(provider: AgentsContextProvider): string {
  if (!provider.aliases || provider.aliases.length === 0) {
    return provider.name;
  }
  return `${provider.name} (${provider.aliases.join(', ')})`;
}

function formatProviderDescription(
  description: string,
  termWidth: number,
): string {
  return description.replace(/\n/g, `\n${' '.repeat(termWidth + 2)}`);
}

function selectAgentsContextProviders(
  provider?: string,
  runAll = false,
): AgentsContextProvider[] {
  if (runAll) {
    return agentsContextProviders.filter((provider) => provider.default);
  }
  if (!provider) {
    throw new Error(
      `Specify an agents context provider or use --all.\n\n${formatAgentsContextProviders()}`,
    );
  }
  const selectedProvider = agentsContextProviders.find(
    (candidate) =>
      candidate.name === provider || candidate.aliases?.includes(provider),
  );
  if (!selectedProvider) {
    throw new Error(
      `Unknown agents context provider '${provider}'. Available providers: ${agentsContextProviders.map((candidate) => candidate.name).join(', ')}.`,
    );
  }
  return [selectedProvider];
}
